ufs_dict = {
    "bahia": "BAHIA",
    "amapa": "AMAPÁ",
    "maranhao": "MARANHÃO",
    "rio-grande-do-sul": "RIO GRANDE DO SUL",
    "paraiba": "PARAÍBA",
    "distrito-federal": "DISTRITO FEDERAL",
    "tocantins": "TOCANTINS",
    "pernanbuco": "PERNAMBUCO",
    "piaui": "PIAUÍ",
    "roraima": "RORAIMA",
    "minas-gerais": "MINAS GERAIS",
    "amazonas": "AMAZONAS",
    "acre": "ACRE",
    "goias": "GOIÁS",
    "ceara": "CEARÁ",
    "espirito-santo": "ESPÍRITO SANTO",
    "santa-catarina": "SANTA CATARINA",
    "alagoas": "ALAGOAS",
    "rondonia": "RONDÔNIA",
    "rio-de-janeiro": "RIO DE JANEIRO",
    "sao-paulo": "SÃO PAULO",
    "sergipe": "SERGIPE",
    "para": "PARÁ",
    "mato-grosso-do-sul": "MATO GROSSO DO SUL",
    "parana": "PARANÁ",
    "mato-grosso": "MATO GROSSO",
    "rio-grande-do-norte": "RIO GRANDE DO NORTE"
}
