"""table_name changed

Revision ID: 383bc9da3e36
Revises: 6db9711e87b2
Create Date: 2021-01-14 10:08:57.985140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383bc9da3e36'
down_revision = '6db9711e87b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_data', sa.Column('month_energy', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('energy_data', 'month_energy')
    # ### end Alembic commands ###
