"""empty message

Revision ID: 5f5fdd450143
Revises: ac580e14b7c7
Create Date: 2021-01-11 23:24:23.618733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5fdd450143'
down_revision = 'ac580e14b7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hsp_city_key', 'hsp', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('hsp_city_key', 'hsp', ['city'])
    # ### end Alembic commands ###
