"""db mockup relation simulation

Revision ID: 6db9711e87b2
Revises: 2affaab090b9
Create Date: 2021-01-13 10:05:56.143121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db9711e87b2'
down_revision = '2affaab090b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'simulation', 'lead', ['lead_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'simulation', type_='foreignkey')
    op.drop_column('simulation', 'lead_id')
    # ### end Alembic commands ###
