"""vinicius upgrade

Revision ID: 7fac486fc36f
Revises: 174b5539f18a
Create Date: 2021-01-21 14:09:34.312621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fac486fc36f'
down_revision = '174b5539f18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'seller', 'lead', ['lead_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seller', type_='foreignkey')
    op.drop_column('seller', 'lead_id')
    # ### end Alembic commands ###
