"""added data column into simulation model

Revision ID: a988a4642147
Revises: 
Create Date: 2021-01-19 12:52:28.770024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a988a4642147'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_data', sa.Column('month_value', sa.Numeric(), nullable=False))
    op.add_column('message', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.drop_constraint('message_lead_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'seller', ['seller_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'message', 'lead', ['lead_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('simulation', sa.Column('eletric_materials_cost', sa.Numeric(), nullable=False))
    op.add_column('simulation', sa.Column('energy_cost', sa.Numeric(), nullable=False))
    op.add_column('simulation', sa.Column('inversor_id', sa.Integer(), nullable=True))
    op.add_column('simulation', sa.Column('maintanance_cost', sa.Numeric(), nullable=False))
    op.add_column('simulation', sa.Column('panel_id', sa.Integer(), nullable=True))
    op.add_column('simulation', sa.Column('panel_quantity', sa.Numeric(), nullable=False))
    op.add_column('simulation', sa.Column('project_cost', sa.Numeric(), nullable=False))
    op.add_column('simulation', sa.Column('roi_years', sa.Numeric(), nullable=False))
    op.add_column('simulation', sa.Column('system_cost', sa.Numeric(), nullable=False))
    op.add_column('simulation', sa.Column('total_system_cost', sa.Numeric(), nullable=False))
    op.add_column('simulation', sa.Column('worker_cost', sa.Numeric(), nullable=False))
    op.create_foreign_key(None, 'simulation', 'panel_price', ['panel_id'], ['id'])
    op.create_foreign_key(None, 'simulation', 'inverter_price', ['inversor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'simulation', type_='foreignkey')
    op.drop_constraint(None, 'simulation', type_='foreignkey')
    op.drop_column('simulation', 'worker_cost')
    op.drop_column('simulation', 'total_system_cost')
    op.drop_column('simulation', 'system_cost')
    op.drop_column('simulation', 'roi_years')
    op.drop_column('simulation', 'project_cost')
    op.drop_column('simulation', 'panel_quantity')
    op.drop_column('simulation', 'panel_id')
    op.drop_column('simulation', 'maintanance_cost')
    op.drop_column('simulation', 'inversor_id')
    op.drop_column('simulation', 'energy_cost')
    op.drop_column('simulation', 'eletric_materials_cost')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_lead_id_fkey', 'message', 'lead', ['lead_id'], ['id'])
    op.drop_column('message', 'seller_id')
    op.drop_column('energy_data', 'month_value')
    # ### end Alembic commands ###
