"""create table message, change lead table

Revision ID: dad503ce998e
Revises: 5202a6259b2a
Create Date: 2021-01-14 12:17:36.621635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad503ce998e'
down_revision = '5202a6259b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lead', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('lead', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('lead', 'name')
    op.drop_table('message')
    # ### end Alembic commands ###
