"""empty message

Revision ID: de33cc4ccfaf
Revises: f5d9c32c20ca
Create Date: 2021-01-11 21:42:52.145968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de33cc4ccfaf'
down_revision = 'f5d9c32c20ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=10), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panel_price')
    # ### end Alembic commands ###
