"""migrations in table update

Revision ID: e3354e0b85da
Revises: 1c2a2efc2418
Create Date: 2021-01-19 09:24:35.220813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3354e0b85da'
down_revision = '1c2a2efc2418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.drop_constraint('message_lead_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'seller', ['seller_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'message', 'lead', ['lead_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_lead_id_fkey', 'message', 'lead', ['lead_id'], ['id'])
    op.drop_column('message', 'seller_id')
    # ### end Alembic commands ###
